name: Smart Contract Audit

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Securify
      uses: ethereum/actions/setup-securify@v1.0.0

    - name: Run Securify analysis
      run: securify ./contracts/*.sol

    - name: Review Securify results
      uses: ethereum/actions/securify-review@v1.0.0
      with:
        securify-report-path: ./securify_report.json
