name: Securify Audit

on:
  push:
    branches:
      - master

jobs:
  securify-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python
      run: sudo apt-get -y install python3 python3-pip python3-distutils
      
    - name: Clone Securify repository
      run: git clone https://github.com/eth-sri/securify2.git
      
    - name: Install Securify dependencies
      run: cd securify2 && pip3 install -r requirements.txt
      
    - name: Install Securify dependencies
      run: cd securify2 && python3 setup.py install --user
    - name: Install dependencies
      run: |
          sudo snap install solc
          python -m pip install --upgrade pip
          pip install slither-analyzer==0.8.1 solc-select==0.2.1
              
    - name: Analyze Solidity contract with Securify
      run:  cd contracts && securify dummy.sol | grep "potential vulnerability"
