name: Securify

on:
  push:
    branches: [master]
    paths:
      - 'contracts/**/*.sol'

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Securify
        run: |
          git clone https://github.com/eth-sri/securify2.git
          cd securify2
          npm install
      - name: Run Securify
        run: |
          python3 securify.py -d ${{ github.workspace }}/contracts -o ${{ github.workspace }}/report.json
      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: securify-report
          path: ${{ github.workspace }}/report.json
