name: Smart Contract Audit

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    container: ethereum/solc:0.5.2
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Securify
      run: |
        sudo apt-get update && \
        sudo apt-get install -y curl && \
        curl -sL https://github.com/eth-sri/securify/releases/download/v0.4.3/securify-linux -o /usr/local/bin/securify && \
        chmod +x /usr/local/bin/securify

    - name: Run Securify analysis
      run: securify ./contracts/*.sol
