name: Securify Audit

on:
  push:
    branches:
      - master

jobs:
  securify-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python
      run: sudo apt-get -y install python3 python3-pip python3-distutils
      
    - name: Clone Securify repository
      run: git clone https://github.com/eth-sri/securify2.git
      
    - name: Install Securify dependencies
      run: cd securify2 && pip3 install -r requirements.txt
      
    - name: Install Solec
      run: |
            sudo add-apt-repository ppa:ethereum/ethereum
            sudo apt-get update
            sudo apt-get install solc
      
    - name: Install Securify dependencies
      run: cd securify2 && python3 setup.py install --user
      
    - name: Install dependencies
      run: |
         sudo apt-get update
         sudo apt-get install -y gcc g++ libssl-dev python3-dev
    - name: Install securify
      run: pip install securify
    - name: Set up LD_LIBRARY_PATH
      run: export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/path/to/securify/libfunctors"

    - name: Compile contract
      run: cd contracts && securify dummy.sol | grep "potential vulnerability"
