name: Smart Contract Audit

on:
  push:
    branches: [ master ] # replace "main" with your default branch name
  pull_request:
    branches: [ master ] # replace "main" with your default branch name

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Truffle and other dependencies
        run: npm install -g truffle && npm install

      - name: Compile contracts
        run: truffle compile

      - name: Run security analysis
        uses: trailofbits/sol-analyzer@v0.6.0
        with:
          contract: ./build/contracts/*.json # replace with the path to your contract artifacts
          rule: high # change this to the desired rule level (high, medium, or low)
          format: json # change this to the desired output format (text or json)

      - name: Upload security report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: security-report
          path: security_report.json # replace with the name of the output file from the previous step
