name: Securify Scan
on:
  push:
    branches:
      - master

jobs:
  securify-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: securify
    - name: Run Securify
      run: |
        docker run --rm -v $PWD:/code securify /code

    - name: Upload Report to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: securify-report
        path: report.json
