name: Smart Contract Audit Workflow

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Securify
      uses: ethereum-security-tools/securify@v1.1.1

    - name: Run Securify
      run: securify --list-vulnerabilities --solc-version 0.8.6 contracts/*.sol

    - name: Upload Report to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: securify-report
        path: report.json
