name: Smart Contract Audit

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Securify analysis
      run: |
        docker run -v $PWD:/contracts ethereum/solc:0.5.2 securify /contracts/*.sol > securify_report.json

    - name: Print Securify report
      run: /bin/bash -c "tail -n +2 securify_report.json"
