name: Securify Audit

on:
  push:
    branches:
      - master

jobs:
  securify-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Securify
      run: |
        sudo apt-get update
        sudo apt-get -y install python3 python3-pip
        sudo apt-get -y install python3-distutils
        sudo pip3 install securify
        
    - name: Analyze Solidity contract with Securify
      run: |
        securify .
