- name: Deep Security Smart Check Scan Action
  # You may pin to the exact commit or the version.
  # uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@e09ec08e774f2f41410aeffb5cb1695003c08b37
  uses: felipecosta09/Deep-Security-Smart-Check-Scan-Action@v1.0.3
  with:
    # Container repository, eg myorg/myimage.
    DSSC_IMAGE_NAME: 
    # Deep Security Smart Check url, eg mydomain.com.
    DSSC_SMARTCHECK_HOST: 
    # Deep Security Smart Check username, eg admin.
    DSSC_SMARTCHECK_USER: 
    # (MANDATORY) Deep Security Smart Check password, eg 12345.
    DSSC_SMARTCHECK_PASSWORD: 
    # (MANDATORY) Container registry credentials in a json format,  eg '{"username":"<user>","password":"<password>"}' or {"aws":{"region":"us-east-1","accessKeyID":"'AWS_ACCESS_KEY_ID'","secretAccessKey":"'AWS_SECRET_ACCESS_KEY'"}}'
    DSSC_IMAGE_PULL_AUTH: 
    # (OPTIONAL) If the client should ignore certificate errors when connecting to Deep Security Smart Check. You may want to set this if you've configured a self signed cert. eg true
    DSSC_INSECURE_SKIP_TLS_VERIFY: # optional, default is true
    # (OPTIONAL) If Deep Security Smart Check should ignore certificate errors from the image registry. eg true
    DSSC_INSECURE_SKIP_REGISTRY_TLS_VERIFY: # optional, default is true
    # (OPTIONAL) Specify this option to trigger a "pre-registry scan", which pushes the image to a temporary registry on the scan system.
    DSSC_PREREGISTRY_SCAN: # optional
    # (OPTIONAL) The hostname of the temporary registry. Defaults to the smartcheck-host on port 5000.
    DSSC_PREREGISTRY_HOST: # optional
    # (OPTIONAL) The username to authenticate with the temporary registry.
    DSSC_PREREGISTRY_USER: # optional
    # (OPTIONAL) The password to authenticate with the temporary registry.
    DSSC_PREREGISTRY_PASSWORD: # optional
    # (OPTIONAL) The path to write the scan results to. If not provided, the scan results will be written to stdout.
    DSSC_RESULTS_FILE: # optional
    # (OPTIONAL) A JSON object that can be used to fail this step if an image contains findings that exceed the threshold.
    DSSC_FINDINGS_THRESHOLD: # optional
