name: Static Analysis SmartCheck
on:
  push:
    branches: [master]
    paths:
      - "contracts/**"
      - ".github/workflows/dummy.yaml"
  pull_request:
    branches: [master]
    paths:
      - "contracts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      
      - name: Install dependencies
        run: sudo npm install @smartdec/smartcheck -g

      - name: Summary of static ananlysis using smart check
        run: sudo smartcheck -p .
          
      - name: Upload report as artifact
        uses: actions/upload-artifact@v2
        with:
            name: smarctcheck-report
            path: /home/runner/work/SrihariDemo-smartcheck/SrihariDemo-smartcheck/build/contracts
            
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
           name: smarctcheck-report
           path: /home/runner/work/SrihariDemo-smartcheck/SrihariDemo-smartcheck/build/contracts    
      
      -  name: Upload SARIF file
         uses: github/codeql-action/upload-sarif@v2
         with:
           sarif_file:  ${{ steps.smarctcheck.outputs.sarif }}
                  
      - name: Upload smarctcheck report
        uses: actions/upload-artifact@v2
        with:
         name: smarctcheck report
         path: report.json
