name: Securify Audit

on:
  push:
    branches:
      - master

jobs:
  securify-analysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Python
      run: sudo apt-get -y install python3 python3-pip python3-distutils
      
    - name: Clone Securify repository
      run: git clone https://github.com/eth-sri/securify.git
      
    - name: Install Securify dependencies
      run: cd securify && pip3 install -r requirements.txt
      
    - name: Install Securify
      run: cd securify && python3 setup.py install
        
    - name: Analyze Solidity contract with Securify
      run: |
        cd contracts
        securify dummy.sol
