name: SmartCheck Workflow

on:
  push:
    branches:
      - master

jobs:
  smartcheck-scan:
    name: SmartCheck Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start SmartCheck scan
        uses: deepsecurity/smartcheck-action@v1
