name: Smart Contract Audit Workflow

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Securify
      run: |
        wget https://github.com/eth-sri/securify/releases/latest/download/securify-linux
        chmod +x securify-linux
        sudo mv securify-linux /usr/local/bin/securify

    - name: Run Securify
      run: securify --list-vulnerabilities --solc-version 0.8.6 contracts/*.sol

    - name: Upload Report to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: securify-report
        path: report.json
