name: Securify Audit

on:
  push:
    branches: [master]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build -t securify-audit .
    - name: Run Securify audit
      run: docker run -v "$(pwd):/contract" securify-audit /contract/dummy.sol

    - name: Upload Report to GitHub
      uses: actions/upload-artifact@v2
      with:
        name: securify-report
        path: report.json
