name: Securify Audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Securify
      run: pip install securify

    - name: Run Securify audit
      run: securify -i contracts/ -o reports/
