name: Securify
on: push

jobs:
  securify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t securify .
      - name: Run Securify analysis
        run: docker run /code securify securify /code
