name: Smart Contract Audit

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Java and Maven
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jdk maven

    - name: Check if Securify directory exists
      run: |
        if [ ! -d "securify" ]; then
          echo "Securify directory not found, cloning repository..."
          git clone https://github.com/eth-sri/securify.git
        fi

    - name: Build Securify tool
      working-directory: ./securify
      run: |
        cd securify
        mvn clean package -DskipTests

    - name: Run Securify analysis
      run: |
        ./securify/scripts/securify ./contracts/*.sol > securify_report.json

    - name: Print Securify report
      run: /bin/bash -c "tail -n +2 securify_report.json"
