name: Smart Contract Audit

on:
  push:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Securify directory if not exists
      run: |
        mkdir -p securify

    - name: Clone Securify repository
      if: steps.create_securify_dir.outputs.status == 'success'
      run: |
        git clone https://github.com/eth-sri/securify.git securify

    - name: Build Securify tool
      run: |
        if [ -f securify/pom.xml ]; then
          cd securify
          mvn clean package -DskipTests
        else
          echo "ERROR: No pom.xml file found in securify directory"
          exit 1
        fi

    - name: Run Securify analysis
      run: |
        ./securify/scripts/securify ./contracts/*.sol > securify_report.json

    - name: Print Securify report
      run: /bin/bash -c "tail -n +2 securify_report.json"

    - name: Set output
      id: create_securify_dir
      run: echo "::set-output name=status::$(if [ -d securify ]; then echo 'exists'; else echo 'created'; fi)"
