name: Solidity Security Analysis

on: push

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Python & Securify
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install securify

      - name: Analyze Contract
        run: securify contracts/dummy.sol
