name: Static Analysis SmartCheck
on:
  push:
    branches: [master]
    paths:
      - "contracts/**"
      - ".github/workflows/dummy.yaml"
  pull_request:
    branches: [master]
    paths:
      - "contracts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install Securify
        run: |
          git clone https://github.com/eth-sri/securify2.git
          cd securify2
          npm install
      - name: Run Securify
        run: |
          python3 securify.py -d ${{ github.workspace }}/contracts -o ${{ github.workspace }}/report.json
